# This redeploys the go-app container in every commit
---
- hosts: 172.31.32.36
  tasks:

  - name: Log into private regis
    docker_login:
      registry: registry.ombada.tech:5000
      username: docker-user
      password: Brezn4ME!
      reauthorize: yes

  - name: Create website container
    docker_container:
      name: test-website
      image: registry.ombada.tech:5000/test-jenkins-go
      pull: yes
      restart_policy: always
      hostname: test-website
      ports:
        - "8088:8080"
    tags:
      - redeploy

  - name: make sure packages exists
    package:
      name: "{{item}}"
      state: present
    with_items:
      - nginx

  - name: copy config files 
    ansible.builtin.template:
      src: server-config.j2
      dest: /etc/nginx/sites-available/default.conf
      owner: root
      group: root
      mode: '0644'

  - name: create sym links
    file:
      src: /etc/nginx/sites-available/default.conf
      dest: /etc/nginx/sites-enabled/default.conf
      owner: root
      group: root
      state: link

  - name: force systemd to reread configs
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: enable nginx 
    shell: "systemctl enable nginx" 

  - name: start nginx 
    shell: "systemctl start nginx"
