---
- name: update cache
  apt:
    update_cache: yes
  become: true

- import_tasks: dependencies.yml

- name: Download go
  get_url:
    url: https://go.dev/dl/go1.17.5.linux-amd64.tar.gz
    dest: /home/ahmed.ombada
    mode: '0644'

- name: remove a previous installation at /usr/local/go
  shell: rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz


- name: copy binaries
  copy:
    src: "/usr/local/go/bin/go"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes

- name: add jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key 
    state: present
  ignore_errors: true

- name: append source list
  shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: install jenkins
  apt:
    pkg: jenkins
    state: latest
    update_cache: yes
  become: true

- name: Start service jenkins, if not started
  ansible.builtin.service:
    name: jenkins
    state: started

# generate keys later