# Playbook to manage freeradius servers

- name: lets get this thing going
  hosts: jenkins
  become: yes
  roles:
    - jenkins
  tags:
    - jenkins

- name: deploy
  hosts: webservers
  become: yes
  roles:
    # - nginx
    - docker
    - deploy-app
  tags:
    - deploy-app